services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2556:3000"
    volumes:
      - ./src:/usr/src/app/src
    environment:
      SERVER_PORT: ${SERVER_PORT}
      STATIC_DIR: ${STATIC_DIR}
      NODE_ENV: production
    restart: always

networks:
  default:
    driver: bridge