services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVER_PORT: ${SERVER_PORT}
    ports:
      - "${DOCKER_PORT}:${SERVER_PORT}"
    volumes:
      - ./:/usr/src/app/
    environment:
      SERVER_PORT: ${SERVER_PORT}
      NODE_ENV: production
    restart: always

networks:
  default:
    driver: bridge