services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVER_PORT: ${SERVER_PORT}
    ports:
      - "2556:3000"
    volumes:
      - ./src:/usr/src/app/src
      -  ${STATIC_DIR}:/usr/src/app/static
    environment:
      SERVER_PORT: ${SERVER_PORT}
      NODE_ENV: production
    restart: always

networks:
  default:
    driver: bridge